# Generated by Django 3.0.5 on 2020-05-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200503_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
