# Generated by Django 3.0.5 on 2020-05-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisite',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
