# Generated by Django 3.0.5 on 2020-05-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='admin_meessage',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='user_meessage',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
