# Generated by Django 3.0.5 on 2020-05-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170122_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
